#import "/src/setup.typ": *
#show: note

= Fourier Transform and Translations

The Fourier transform is naturally defined on locally compact abelian groups.
The most natural setting is Euclidean space $RR^n$
with the additive group $(RR^n, +)$, encoding translational symmetry.

== Translations as a Representation

The group $(RR^n, +)$ is a Lie group: a smooth manifold with a smooth group operation.
Its Lie algebra
$
  frak(g) = T_0 RR^n tilde.equiv RR^n, quad [X, Y] = 0
$
carries the trivial bracket, reflecting commutativity.
The exponential map $exp: frak(g) -> G$ is the identity $X |-> X$,
since the one-parameter subgroup generated by $X$ is $t |-> t X$.

We define translation operators ${T_a}_(a in RR^n)$ acting on $L^2(RR^n)$ by
$
  T_a f(x) = f(x - a).
$
The map $rho: (RR^n, +) -> op("GL")(L^2(RR^n))$, $rho(a) = T_a$,
is a unitary representation of $(RR^n, +)$:
$
  rho(a + b) = T_(a+b) = T_a T_b = rho(a) rho(b), quad rho(0) = op("id").
$

== Eigenpairs of Translation

We seek eigenpairs: functions $phi$ and eigenvalues $lambda(a)$ satisfying
$
  T_a phi = lambda(a) phi quad "for all" a in RR^n.
$
Diagonalizing a single operator yields a scalar eigenvalue $lambda in CC$.
Here we simultaneously diagonalize the entire family ${T_a}_(a in RR^n)$,
so the eigenvalue is a function $a |-> lambda(a)$
--- a consistent assignment across all group elements.

The group law and unitarity fully determine $lambda$.
From $T_a T_b = T_(a+b)$:
$
  lambda(a) lambda(b) phi = T_a T_b phi = T_(a+b) phi = lambda(a + b) phi
  quad ==> quad
  lambda(a + b) = lambda(a) lambda(b).
$
From unitarity:
$
  abs(lambda(a)) norm(phi) = norm(lambda(a) phi) = norm(T_a phi) = norm(phi)
  quad ==> quad
  abs(lambda(a)) = 1.
$

So $lambda: (RR^n, +) -> U(1)$ must be a continuous group homomorphism
into the unit circle --- a _character_ of the group.
The multiplicativity and unit modulus are not definitions;
they are forced by the group law and unitarity.

The unique family of continuous solutions is
$
  lambda(a) = chi_xi (a) = e^(i inner(xi, a)), quad xi in RR^n
$
with corresponding eigenfunction
$
  phi_xi (x) = e^(i inner(xi, x)).
$
Verification:
$
  T_a phi_xi (x)
  = e^(i inner(xi, x - a))
  = chi_xi (-a) phi_xi (x).
$
The parameter $xi$ labels the character and becomes the frequency variable.
Each $phi_xi$ spans a one-dimensional invariant subspace of $L^2$
--- an irreducible subrepresentation.

_Remark._
That irreducible representations of abelian groups are one-dimensional
follows from Schur's lemma:
every operator commuting with all of an irreducible representation
must be a scalar, so in an abelian group each $rho(a)$ acts as a scalar,
forcing $dim = 1$.

== Fourier Transform as Change of Basis

Since the translation group is abelian,
the operators $T_a$ commute and can be simultaneously diagonalized.
The Fourier transform is the change of basis into this joint eigenbasis.

Analysis --- project onto each eigenfunction:
$
  hat(f)(xi) = inner(f, phi_xi)_(L^2) = integral_(RR^n) f(x) overline(phi_xi (x)) dif x.
$

Synthesis --- reconstruct from components:
$
  f(x)
  = integral_(RR^n) inner(f, phi_xi)_(L^2) phi_xi (x) dif xi
  = integral_(RR^n) hat(f)(xi) phi_xi (x) dif xi.
$

This is the continuous analogue of $v = sum_i inner(v, e_i) e_i$
with the discrete index $i$ replaced by the continuous parameter $xi in RR^n$.
Parseval's theorem
$
  norm(f)_(L^2) = norm(hat(f))_(L^2)
$
expresses unitarity of this basis change,
analogous to $norm(v)^2 = sum_i abs(inner(v, e_i))^2$.

== Derivatives and Convolutions

The group representation $rho$ induces a Lie algebra representation
$dif rho: frak(g) -> frak(g frak(l))(L^2)$
via infinitesimal generators.
The basis vector $e_j in frak(g)$ acts as
$
  dif rho(e_j) f = dif / (dif t) bar_(t = 0) rho(e^(t e_j)) f = dif / (dif t) bar_(t = 0) T_(t e_j) f = -partial_(x_j) f.
$
The operator exponential recovers the group representation,
mirroring $exp: frak(g) -> G$ at the operator level:
$
  T_a = rho(a) = e^(dif rho(a)) = exp(-a^j partial_(x_j)).
$

Since the Fourier transform diagonalizes the group action,
it must also diagonalize the Lie algebra action:
$
  cal(F)[partial_(x_j) f](xi) = i xi_j hat(f)(xi).
$
These are consistent: exponentiating the algebra eigenvalue
$-i xi_j a^j$ recovers the group eigenvalue $e^(-i xi_j a^j)$.

Constant-coefficient PDEs, built from these generators,
become algebraic in Fourier space.

Convolution operators
$
  (A f)(x) = integral k(x - y) f(y) dif y
$
are exactly the translation-invariant linear maps, i.e. $A T_a = T_a A$.
Any operator commuting with all translations
must act as a scalar on each eigenspace,
so convolution becomes multiplication in Fourier space:
$
  cal(F)[k * f] = hat(k) hat(f).
$

Read the other way, a convolution is a slid inner product.
Given the $L^2$ inner product $inner(f, g) = integral f(x) g(x) dif x$,
the convolution is the same thing with one function shifted,
where the shift is the input,
$
  (f * g)(t) = integral f(x) g(x - t) dif x,
$
so there is a convolution to every inner product.
Inner products measure similarity of elements of a linear space:
for vectors in $RR^d$ this is their alignment,
for functions it is how well they overlap over the whole domain.
Convolution measures that similarity in a shifted manner,
and if one of the two functions is spatially confined, a wavelet say,
the measurement becomes local.

== Other Groups

The same construction applies to any locally compact abelian group:

#table(
  columns: (auto, auto),
  align: (center, left),
  stroke: 0.5pt,
  table.header[$G$][Transform],
  [$RR^n$], [Fourier transform],
  [$TT^n$], [Fourier series],
  [$ZZ$], [Discrete-time Fourier transform],
  [$ZZ slash n ZZ$], [DFT],
)

== Generalization to Manifolds

On a general Riemannian manifold $(M, g)$ there is no group structure
and hence no translations.
The entire character-based construction breaks down.

However, the Laplace--Beltrami operator $Delta_g$
is intrinsically defined on any $(M, g)$.
On $RR^n$, diagonalizing $Delta$ and diagonalizing translations
yield the same eigenbasis,
since $Delta = sum_j partial_(x_j)^2$
is built from the generators of translation.

On a general manifold, we take the spectral decomposition of $Delta_g$
as the _definition_ of a generalized Fourier transform.
For compact $M$, the spectrum is discrete:
$
  Delta_g phi_k = -lambda_k phi_k, quad 0 = lambda_0 <= lambda_1 <= lambda_2 <= dots
$
and ${phi_k}$ forms an orthonormal eigenbasis for $L^2(M)$.
The eigenvalue $lambda_k$ plays the role of $abs(xi)^2$,
but the directional information encoded in $xi in RR^n$ is lost.
